### ISSUE TITLE
Error when start master

### ISSUE THREAD

**Issue by serefercelik** [GENERALBYTESCOM/batm_public#180]
Hi, we're trying start master : 

`/batm/batm-manage fg master`

`....
2019-03-05 12:09:19.563 [main] DEBUG batm.master.ExtensionsSupport - Loaded 74 other extensions.
2019-03-05 12:09:19.577 [main] INFO  batm.master.ExtensionsSupport - Loaded watchlists (3):[OFAC - Specially Designated Nationals List, EU - Financial Sanctions, Czech - Sanction List]
Exception in thread "main" java.lang.NoClassDefFoundError: com/generalbytes/batm/common/currencies/CryptoCurrency
	at com.generalbytes.batm.server.extensions.extra.bitcoin.BitcoinExtension.getSupportedCryptoCurrencies(BitcoinExtension.java:244)
	at com.generalbytes.batm.server.extensions.e.b(GB:368)
	at com.generalbytes.batm.server.services.e.a(GB:2094)
	at com.generalbytes.batm.server.ServerMain.main(GB:7)
Caused by: java.lang.ClassNotFoundException: com.generalbytes.batm.common.currencies.CryptoCurrency
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 4 more
`

How we can fix this problem?

**Comment by moorbsen** [comment]
I had this issue to. You need to copy your currency snapshot into the master/lib folder

**Comment by rpanak-generalbytes** [comment]
Use the latest source code.
