### ISSUE TITLE
[BUS-2000] batm.master.exchange.DVChain - DVChain exchange balance request: USD java.lang.NullPointerException: null

### ISSUE THREAD

**Issue by ztnark** [GENERALBYTESCOM/batm_public#208]
Hello, our client is having an issue connecting the ATM to our exchange (DVChain). The issue is below. 

Should I just return 0 in this case?

Also, would it be possible for me to get a "virtual terminal" to test test the ATM flow against DVChain?

```[BUS-2000] batm.master.exchange.DVChain - DVChain exchange balance request: USD
java.lang.NullPointerException: null
at com.generalbytes.batm.server.extensions.extra.bitcoin.exchanges.XChangeExchange.getFiatBalance(XChangeExchange.java:182)
at com.generalbytes.batm.server.services.d.b(GB:307)
at com.generalbytes.batm.server.services.d.testTerminalConfiguration(GB:4285)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.caucho.hessian.server.HessianSkeleton.invoke(HessianSkeleton.java:192)
at com.caucho.hessian.server.HessianSkeleton.invoke(HessianSkeleton.java:110)
at com.generalbytes.bus.impl.BusService.handle(BusService.java:72)
at com.generalbytes.bus.impl.BusService.access$100(BusService.java:17)
at com.generalbytes.bus.impl.BusService$1.run(BusService.java:102)
at java.lang.Thread.run(Thread.java:748)```

**Comment by ztnark** [comment]
I've opened a case with support.
