### ISSUE TITLE
The implementation tester does not run under Java 10 due to missing java.xml.bind

### ISSUE THREAD

**Issue by JKAbrams** [GENERALBYTESCOM/batm_public#230]
There is a problem preventing to run the tester on Java 10 (and I think but have not verified on Java 9).

```
./server_extensions_test/build/install/server_extensions_test/bin/server_extensions_test -a list-ratesources
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
        at com.generalbytes.batm.server.extensions.extra.watchlists.BasicWatchlistsExtension.<init>(BasicWatchlistsExtension.java:31)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
        at java.base/java.lang.Class.newInstance(Class.java:560)
        at com.generalbytes.batm.server.extensions.test.Tester.loadExtensionsFromFile(Tester.java:223)
        at com.generalbytes.batm.server.extensions.test.Tester.loadExtensions(Tester.java:194)
        at com.generalbytes.batm.server.extensions.test.Tester.go(Tester.java:122)
        at com.generalbytes.batm.server.extensions.test.Tester.main(Tester.java:49)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
        ... 10 more
```

```
java --version
openjdk 10.0.2 2018-07-17
```

The issue and workarounds are described in detail here:
https://stackoverflow.com/questions/46084751/how-to-express-dependency-in-maven-on-java-ee-features-for-transition-to-java-9

Adding this line to dependencies{} in **server_extensions_test/build.gradle** makes it run:

```
dependencies {
    compile project(':server_extensions_api');
    compile project(':server_extensions_extra');
    compile(group: 'net.sf.jopt-simple', name: 'jopt-simple', version: '4.9')

    // Java 10 fix
    compile(group: 'javax.xml.bind', name: 'jaxb-api', version: '2.3.0')

    runtime(group: 'org.slf4j', name: 'slf4j-simple', version: '1.7.25')
}
```

As well as the corresponding module hash in **dependencyChecksums.txt**

```
// Java 10 fix
verifyModule 'javax.xml.bind:jaxb-api:2.3.0:883007989d373d19f352ba9792b25dec21dc7d0e205a710a93a3815101bb3d03'
```

**Comment by generalbytes** [comment]
Thank you for the solution.
However BATM server and extensions must be run in production on Java 8 due.
There are other components that require it to be run with Java 8.
I encourage you to run your tests and extensions development in Java 8 enviroment.
