### ISSUE TITLE
Questions about the way currencies.jar works

### ISSUE THREAD

**Issue by makarid** [GENERALBYTESCOM/batm_public#409]
Hello again, please do not close an issue immediately. Thank you for your understanding

This is the errors that i get:

08/11/2020 11:30:50 AM WARN
[src/_views/crypto_settings/form.jsp] (default task-9) error - get crypto currency name for TOKEN1
08/11/2020 11:30:55 AM WARN
[src/ajax/terminal_action_crypto.jsp] (default task-9) error - get crypto currency name for TOKEN1
08/11/2020 11:31:18 AM INFO
[src/_views/crypto_settings/process.jsp] (default task-12) Crypto Setting 'TOKEN1' was modified by 'admin'
08/11/2020 11:31:36 AM WARN
[src/_views/terminals/form.jsp] (default task-9) error - get crypto currency name for TOKEN1
08/11/2020 11:32:09 AM INFO
[src/_views/terminals/process_modify.jsp] (default task-9) Terminal 'BTXXXXX' was modified by 'admin'
08/11/2020 11:32:18 AM WARN
[src/_views/terminals/form.jsp] (default task-9) error - get crypto currency name for TOKEN1
08/11/2020 11:32:51 AM WARN
[src/_views/terminals/form.jsp] (default task-15) error - get crypto currency name for TOKEN1
08/11/2020 11:46:59 AM WARN
[src/_views/terminals/form.jsp] (default task-30) error - get crypto currency name for TOKEN1
08/11/2020 12:21:57 PM WARN
[src/_views/terminals/form.jsp] (default task-49) error - get crypto currency name for TOKEN1

I have put my new currencies.jar on the master/lib/ folder and i have delete the old_currencies.jar file. I can see my newly created token on the Crypto Settings tab and i added a new Crypto Settings without a problem. I run all tests and work, except for the Buy from exchange test, because i haven't implement a exchange(it doesn't needs one with my strategy). I have include this new token on one of my ATMs but even thought i can see the price on the screensaver,there isn't any option to buy it.

Can you please answer my questions:
1) Have i done it correctly?
2) Do i need to add this currencies.jar on the master/extensions/ folder also?
3) Does this error(warn) message prevent the server to offer buying support of this token on my ATMs? I mean is this error crucial for the BUY functionality to work my ATMs?
4) Can you please help me understand why this error is thrown and not close my issue immediately?

I am waiting for your response or any questions/clarifications you need from me. Thank you!

**Comment by makarid** [comment]
Can please someone contact with me. I have send you message on the GB support and the agent told me to write the issue here.

**Comment by pvyhnal-generalbytes** [comment]
```
08/11/2020 11:30:50 AM WARN
[src/_views/crypto_settings/form.jsp] (default task-9) error - get crypto currency name for TOKEN1
```
This means the admin (CAS) application does not have your modified currencies JAR. It should not affect the BUY button on the terminal.

Does the BUY button displays for some other currencies like BTC?

**Comment by makarid** [comment]
Yes, it is displayed for other currencies like BTC. I can see on the screensaver my price of my TOKEN1. But there is no BUY button to buy it. I have add my currencies-1.0.7-SNAPSHOT.jar on the master/lib folder.

**Comment by pvyhnal-generalbytes** [comment]
master (the server which terminals connects to) and admin (CAS - the web application used for configuration) are two separate applications. You added the library to master but this should not be the reason for not displaying the buy button.

Can you see if there are any errors or warnings in your master.log file?

**Comment by makarid** [comment]
I can see only the following errors:
08/14/2020 01:17:48 PM	ERROR	
[»BT100399/getTerminalConfiguration/43] batm.master.TPBasic - getTerminalConfiguration
java.lang.NoSuchFieldError: BSD
at com.generalbytes.batm.common.fiat.Banknotes.<clinit>(Banknotes.java:90)
at com.generalbytes.batm.server.core.b.o.f(GB:813)
at com.generalbytes.batm.server.core.r.getTerminalConfiguration(GB:110)
at com.generalbytes.batm.server.services.web.b.getTerminalConfiguration(GB:134)
at com.generalbytes.batm.trace.BT100399.getTerminalConfiguration(Unknown Source)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.generalbytes.batm.server.services.web.f.invoke(GB:70)
at com.sun.proxy.$Proxy13.getTerminalConfiguration(Unknown Source)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.generalbytes.batm.server.services.web.e.invoke(GB:141)
at com.sun.proxy.$Proxy13.getTerminalConfiguration(Unknown Source)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.generalbytes.batm.server.services.web.g.invoke(GB:99)
at com.sun.proxy.$Proxy13.getTerminalConfiguration(Unknown Source)
at com.generalbytes.batm.server.services.web.d.getTerminalConfiguration(GB:374)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.caucho.hessian.server.HessianSkeleton.invoke(HessianSkeleton.java:192)
at com.caucho.hessian.server.HessianSkeleton.invoke(HessianSkeleton.java:110)
at com.caucho.hessian.server.HessianServlet.service(HessianServlet.java:416)
at com.generalbytes.batm.server.services.web.d.service(GB:179)
at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
at com.generalbytes.batm.server.services.web.a.a.doFilter(GB:23)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
at org.eclipse.jetty.server.Server.handle(Server.java:499)
at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
at com.generalbytes.batm.server.services.web.s.a(GB:59)
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
at java.lang.Thread.run(Thread.java:748)

And:

08/14/2020 01:17:49 PM	ERROR	
[»BT101923/getTerminalConfiguration/41] batm.master.TPBasic - getTerminalConfiguration
java.lang.NoClassDefFoundError: Could not initialize class com.generalbytes.batm.common.fiat.Banknotes
at com.generalbytes.batm.server.core.b.o.f(GB:813)
at com.generalbytes.batm.server.core.r.getTerminalConfiguration(GB:110)
at com.generalbytes.batm.server.services.web.b.getTerminalConfiguration(GB:134)
at com.generalbytes.batm.trace.BT101923.getTerminalConfiguration(Unknown Source)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.generalbytes.batm.server.services.web.f.invoke(GB:70)
at com.sun.proxy.$Proxy13.getTerminalConfiguration(Unknown Source)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.generalbytes.batm.server.services.web.e.invoke(GB:141)
at com.sun.proxy.$Proxy13.getTerminalConfiguration(Unknown Source)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.generalbytes.batm.server.services.web.g.invoke(GB:99)
at com.sun.proxy.$Proxy13.getTerminalConfiguration(Unknown Source)
at com.generalbytes.batm.server.services.web.d.getTerminalConfiguration(GB:374)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.caucho.hessian.server.HessianSkeleton.invoke(HessianSkeleton.java:192)
at com.caucho.hessian.server.HessianSkeleton.invoke(HessianSkeleton.java:110)
at com.caucho.hessian.server.HessianServlet.service(HessianServlet.java:416)
at com.generalbytes.batm.server.services.web.d.service(GB:179)
at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
at com.generalbytes.batm.server.services.web.a.a.doFilter(GB:23)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
at org.eclipse.jetty.server.Server.handle(Server.java:499)
at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
at com.generalbytes.batm.server.services.web.s.a(GB:59)
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
at java.lang.Thread.run(Thread.java:748)

Also there is this info:

	INFO	
[NioClientManager] org.litecoin.Secp256k1Context - java.lang.UnsatisfiedLinkError: no secp256k1 in java.library.path

**Comment by pvyhnal-generalbytes** [comment]
BSD banknotes support was added in the latest version, please update to
20200801

**Comment by makarid** [comment]
I have the latest version (20200801)

**Comment by makarid** [comment]
Can you please tell me what interface or function do i need to implement in order the ATM to offer a buy option on my new token?
I have implement the AbstractExtension.class and i haven't override only the createExchange function. Do i need to implement this function in order the ATM to offer buy option for my token? Right now i have only the default implementation of the AbstractExtension.class

**Comment by pvyhnal-generalbytes** [comment]
Could you make sure you are using the current version of the "batm_public" code?
What Hot Wallet do you use? 
Could you compare your implementation with some other coins added to this repository? For example:
- https://github.com/GENERALBYTESCOM/batm_public/pull/326/files
- https://github.com/GENERALBYTESCOM/batm_public/pull/405/files

**Comment by makarid** [comment]
Hello, my token works now(i can buy it), but i still got this error message on the admin log. Is it crusial?

**Comment by pvyhnal-generalbytes** [comment]
"error - get crypto currency name" in admin.log shouldn't be a problem. It's only for displaying a crypto currency name in admin GUI

**Comment by makarid** [comment]
Thank you very much @pvyhnal-generalbytes for your help and quick responses.
