### ISSUE TITLE
Submit transaction error

### ISSUE THREAD

**Issue by raluik** [GENERALBYTESCOM/batm_public#490]
Hello,

What may be causing this error?

From the terminal events we can see SCREEN TRANSACTION DONE ENTERED, but the transaction doesn't show up in the transactions list and ITransactionListener onTransactionCreated and onTransactionUpdated don't get triggered.

[»BT301283/submitTransaction3/R7UAOM/93] batm.master.TPCryptoAndAltcoins - submitTransactionBuyCryptoInternal (2)
java.lang.NullPointerException: null
at com.generalbytes.batm.server.core.v.a(GB:47)
at com.generalbytes.batm.server.core.b.u.a(GB:2644)
at com.generalbytes.batm.server.core.b.u.a(GB:2180)
at com.generalbytes.batm.server.core.b.u.a(GB:2000)
at com.generalbytes.batm.server.core.r.submitTransaction3(GB:399)
at com.generalbytes.batm.server.services.web.b.submitTransaction3(GB:359)
at com.generalbytes.batm.trace.BT301283.submitTransaction3(Unknown Source)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.generalbytes.batm.server.services.web.f.invoke(GB:72)
at com.sun.proxy.$Proxy61.submitTransaction3(Unknown Source)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.generalbytes.batm.server.services.web.e.invoke(GB:143)
at com.sun.proxy.$Proxy61.submitTransaction3(Unknown Source)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.generalbytes.batm.server.services.web.g.invoke(GB:101)
at com.sun.proxy.$Proxy61.submitTransaction3(Unknown Source)
at com.generalbytes.batm.server.services.web.d.submitTransaction3(GB:336)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at com.generalbytes.batm.server.services.web.b.c.a(GB:86)
at com.generalbytes.batm.server.services.web.b.c.a(GB:34)
at com.generalbytes.batm.server.services.web.b.a.service(GB:287)
at com.generalbytes.batm.server.services.web.d.service(GB:181)
at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
at com.generalbytes.batm.server.services.web.a.a.doFilter(GB:23)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
at org.eclipse.jetty.server.Server.handle(Server.java:499)
at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
at com.generalbytes.batm.server.services.web.s.a(GB:60)
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
at java.lang.Thread.run(Thread.java:748)

**Comment by raluik** [comment]
The problem is gone in server version 20210128
