### ISSUE TITLE
Trying to call addIdentity function but i am getting the following error

### ISSUE THREAD

**Issue by makarid** [GENERALBYTESCOM/batm_public#501]
'could not initialize proxy [com.generalbytes.batm.server.common.data.Organization#1] - no Session' here is the stacktrace:

[»/VS-UNKNOWN/448] org.testserver.RESTSecuredService - could not initialize proxy [com.generalbytes.batm.server.common.data.Organization#1] - no Session
org.hibernate.LazyInitializationException: could not initialize proxy [com.generalbytes.batm.server.common.data.Organization#1] - no Session
at org.hibernate.proxy.AbstractLazyInitializer.initialize(AbstractLazyInitializer.java:169)
at org.hibernate.proxy.AbstractLazyInitializer.getImplementation(AbstractLazyInitializer.java:309)
at org.hibernate.proxy.pojo.bytebuddy.ByteBuddyInterceptor.intercept(ByteBuddyInterceptor.java:45)
at org.hibernate.proxy.ProxyConfiguration$InterceptorDispatcher.intercept(ProxyConfiguration.java:95)
at com.generalbytes.batm.server.common.data.Organization$HibernateProxy$UxmR1xP1.getName(Unknown Source)
at com.generalbytes.batm.server.extensions.a.a.l.a(GB:22)
at com.generalbytes.batm.server.extensions.a.a.g.a(GB:257)
at com.generalbytes.batm.server.extensions.a.a.a(GB:831)
at com.generalbytes.batm.server.extensions.e.addIdentity(GB:740)
at org.testserver.batm.server.extensions.api.RESTSecuredService.addIdentity(RESTSecuredService.java:271)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205)
at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)
at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)
at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305)
at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154)
at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473)
at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427)
at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388)
at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341)
at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228)
at com.generalbytes.batm.server.services.web.l.service(GB:96)
at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
at com.generalbytes.batm.server.services.web.a.a.doFilter(GB:23)
at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
at org.eclipse.jetty.server.Server.handle(Server.java:499)
at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
at com.generalbytes.batm.server.services.web.s.a(GB:60)
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
at java.lang.Thread.run(Thread.java:748)

Have you added any new field that i must implement in order to add a new identity? Thanks

**Comment by makarid** [comment]
i am using the server version 20210128

**Comment by pvyhnal-generalbytes** [comment]
Hi, does this happen when you call `com.generalbytes.batm.server.extensions.IExtensionContext#IIdentity addIdentity(String configurationCashCurrency, String terminalSerialNumber, String externalId, List<ILimit> limitCashPerTransaction, List<ILimit> limitCashPerHour, List<ILimit> limitCashPerDay, List<ILimit> limitCashPerWeek, List<ILimit> limitCashPerMonth, String note, int state, BigDecimal vipBuyDiscount, BigDecimal vipSellDiscount, Date created, Date registered);` method?

Could you share a code snippet or parameter values you use to call the method that causes the exception?

**Comment by makarid** [comment]
Here is my implementation:

                NotRegisteredLimits notRegisteredLimits = new NotRegisteredLimits();
                identity = context.addIdentity(
                    configurationCurrency,
                    TERMINAL_NUMBER,
                    "",
                    notRegisteredLimits.getLimitPerTransaction(),
                    notRegisteredLimits.getLimitPerHour(),
                    notRegisteredLimits.getLimitPerDay(),
                    notRegisteredLimits.getLimitPerWeek(),
                    notRegisteredLimits.getLimitPerMonth(),
                    null,
                    0,
                    BigDecimal.ZERO,
                    BigDecimal.ZERO,
                    Date.from(Instant.now()),
                    Date.from(Instant.now())
                );

**Comment by makarid** [comment]
> Hi, does this happen when you call `com.generalbytes.batm.server.extensions.IExtensionContext#IIdentity addIdentity(String configurationCashCurrency, String terminalSerialNumber, String externalId, List<ILimit> limitCashPerTransaction, List<ILimit> limitCashPerHour, List<ILimit> limitCashPerDay, List<ILimit> limitCashPerWeek, List<ILimit> limitCashPerMonth, String note, int state, BigDecimal vipBuyDiscount, BigDecimal vipSellDiscount, Date created, Date registered);` method?
> 
> Could you compare your code with current examples in this repository?
> https://github.com/GENERALBYTESCOM/batm_public/tree/master/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/examples
> or share a code snippet or parameter values you use to call the method that causes the exception?

Yes, when i use that method

**Comment by makarid** [comment]
> Hi, does this happen when you call `com.generalbytes.batm.server.extensions.IExtensionContext#IIdentity addIdentity(String configurationCashCurrency, String terminalSerialNumber, String externalId, List<ILimit> limitCashPerTransaction, List<ILimit> limitCashPerHour, List<ILimit> limitCashPerDay, List<ILimit> limitCashPerWeek, List<ILimit> limitCashPerMonth, String note, int state, BigDecimal vipBuyDiscount, BigDecimal vipSellDiscount, Date created, Date registered);` method?
> 
> Could you compare your code with current examples in this repository?
> https://github.com/GENERALBYTESCOM/batm_public/tree/master/server_extensions_extra/src/main/java/com/generalbytes/batm/server/extensions/extra/examples
> or share a code snippet or parameter values you use to call the method that causes the exception?

i have copy paste the IdentityExample in order to be sure. But i still getting this error. The error saying about the organisation, can you please tell me what maybe the issue? Thanks
