### ISSUE TITLE
Remote Crypto Buy giving error as "prepareTransaction3 - missing AML2 Collection"

### ISSUE THREAD

**Issue by mxicoderspl** [GENERALBYTESCOM/batm_public#882]
Hello,
When I tried to buy any crypto remotely with the help of the `context.buyCrypto()` method I got this error:- "buyCrypto - Error preparing transaction". It was working fine earlier on the previous versions but I am facing this issue after updating the Server to version '20230801'. We also checked that in AML/KYC everything is properly set or not and everything is properly set. When we perform crypto buys physically on ATMs then we don't get this type of error. The transaction went smoothly without any issues.
We also checked the master logs but in the stack trace, there is not any specific or helpful information found. so please check this and I hope that you will help us to resolve it @generalbytes.

I will mention here the steps that I performed and below it the stack trace of the issue:

Steps that I performed:-
- updated the server version to 20230801 with patch version 50.
- Updated terminal to the same version as of server.
- Installed our custom extensions in GBs server.
- Configured nginx reverse proxy to access the extensions.
- Unpaired and Deleted the ATM from the Server.
- Added new BATM four ATM to the server and configured it properly. Tested it by doing a physical crypto buy.

Stack Trace:-
`<html>
<body>

05.01.2024 11:40:26 | ERROR | [BT301259/0.0.0.0/prepareTransaction3/14764] batm.master.TPCryptoAndAltcoins - prepareTransaction3 - missing AML2 Collection
-- | -- | --
05.01.2024 11:40:26 | ERROR | [BT301259/0.0.0.0/prepareTransaction3/14764] o.b.b.s.e.api.RestSecuredService - buyCrypto - Error preparing transaction. com.generalbytes.batm.server.extensions.exceptions.BuyException: buyCrypto - Error preparing transaction. 	at com.generalbytes.batm.server.extensions.a.a.b(GB:255) 	
at com.generalbytes.batm.server.extensions.f.buyCrypto(GB:558) 	
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 	
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	
at java.lang.reflect.Method.invoke(Method.java:498) 	
at com.generalbytes.batm.server.extensions.c.invoke(GB:39) 	
at com.sun.proxy.$Proxy65.buyCrypto(Unknown Source) 	
at org.bitcoinmat.batm.server.extensions.api.RestSecuredService.buyCryptoAnon(RestSecuredService.java:896) 	
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 	
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 	
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 	
at java.lang.reflect.Method.invoke(Method.java:498) 	
at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) 	
at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) 	
at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) 	
at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205) 	
at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) 	
at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) 	
at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) 	
at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) 	
at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326) 	
at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) 	
at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) 	
at org.glassfish.jersey.internal.Errors.process(Errors.java:315) 	
at org.glassfish.jersey.internal.Errors.process(Errors.java:297) 	
at org.glassfish.jersey.internal.Errors.process(Errors.java:267) 	
at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) 	
at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:305) 	
at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1154) 	
at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:473) 	
at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:427) 	
at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:388) 	
at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:341) 	
at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:228) 	
at com.generalbytes.batm.server.services.web.q.service(GB:97) 	
at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799) 	
at org.eclipse.jetty.servlet.ServletHandler$ChainEnd.doFilter(ServletHandler.java:1626) 	
at org.bitcoinmat.batm.server.extensions.api.CorsFilter.doFilter(CorsFilter.java:46) 	
at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) 	
at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) 	
at com.generalbytes.batm.server.services.web.a.f.doFilter(GB:34) 	
at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) 	
at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) 	
at com.generalbytes.batm.server.services.web.a.e.doFilter(GB:23) 	
at org.eclipse.jetty.servlet.FilterHolder.doFilter(FilterHolder.java:193) 	
at org.eclipse.jetty.servlet.ServletHandler$Chain.doFilter(ServletHandler.java:1601) 	
at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:548) 	
at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) 	
at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624) 	
at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233) 	
at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434) 	
at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188) 	
at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501) 	
at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594) 	
at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186) 	
at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349) 	
at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) 	
at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:59) 	
at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127) 	
at org.eclipse.jetty.server.Server.handle(Server.java:516) 	
at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:388) 	
at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:633) 	
at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:380) 	
at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277) 	
at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311) 	
at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) 	
at org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint.onFillable(SslConnection.java:555) 	
at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:410) 	
at org.eclipse.jetty.io.ssl.SslConnection$2.succeeded(SslConnection.java:164) 	
at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105) 	
at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104) 	
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338) 	
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315) 	
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173) 	
at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131) 	
at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:386) 	
at com.generalbytes.batm.server.services.web.w.a(GB:101) 	
at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883) 	
at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034) 	
at java.lang.Thread.run(Thread.java:750)

</body>
</html>`

**Comment by generalbytes** [comment]
We are sorry but 20230801 is no longer supported as it reached EOL.
Please retest with 20230901. Similar issue has been fixed in 20230901.20 see https://generalbytes.com/patch page.
Please report bugs on support@generalbytes.com as github issues are not checked that often.
